###################################
#             Prison              #
###################################
# 
# Set server MOTD!
server-motd: &8&lPrison Server \n &6Active Staffs/Friendly Community/Custom plugins
#
# 