name: Prison
version: 1.0
author: JrPanda
api-version: 1.13
main: com.Prison.main.Main

commands:
  fly:
    description:
    usage: /fly [player]
    aliases: []
  withdraw:
    description:
    usage: /withdraw <amount>
    aliases: []