name: Prison
version: 1.0
author: JrPanda
api-version: 1.13
main: com.Prison.main.Main

commands:
  fly:
    description:
    usage: /fly [player]
    aliases: []
  withdraw:
    description:
    usage: /withdraw <amount>
    aliases: []
  crates:
    description:
    usage: /crates [args]
    aliases: []
  mod:
    description:
    usage: /mod [args]
    aliases: [ban, kick, warn]
  filetest:
    description:
    usage: /filetest
    aliases: [ft]
  report:
    description:
    usage: /report <player> [args]
    aliases: []